CREATE USER ${datasource.username} WITH ENCRYPTED PASSWORD '${MEDIASERVER.DB.USER.PASSWORD.HASHED}';
CREATE USER ${user.name} WITH ENCRYPTED PASSWORD '*45F9ABB1D55C31BEEE498B353447ABD69F5E1C61';
GRANT ALL PRIVILEGES ON SCHEMA ${JBOSS.SCHEMA} to ${datasource.username};
GRANT ALL PRIVILEGES ON SCHEMA ${MEDIASERVER.SCHEMA} to ${datasource.username};
GRANT ALL PRIVILEGES ON SCHEMA ${JBOSS.SCHEMA} to ${user.name};
GRANT ALL PRIVILEGES ON SCHEMA ${MEDIASERVER.SCHEMA} to ${user.name};