CREATE TABLE `${MEDIADOWNLOADER.SCHEMA}`.`${SERIES.TABLE}` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(100) UNIQUE NOT NULL,
  `season` INT NOT NULL, 
  `episode` INT NOT NULL
  );

CREATE TABLE `${MEDIADOWNLOADER.SCHEMA}`.`${SERIES.DOWNLOAD.TABLE}` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `season` INT NOT NULL, 
  `episode` INT NOT NULL,
  `time` TIMESTAMP NOT NULL,
  UNIQUE (`name`, `season`, `episode`)
  );

ALTER TABLE `${MEDIADOWNLOADER.SCHEMA}`.`${SERIES.DOWNLOAD.TABLE}` ADD UNIQUE INDEX(`name`, `season`, `episode`);
  
CREATE TABLE `${MEDIADOWNLOADER.SCHEMA}`.`${USERS.TABLE}` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(100) UNIQUE NOT NULL,
  `emailaddress` VARCHAR(100) NOT NULL
  );
  
CREATE TABLE `${MEDIADOWNLOADER.SCHEMA}`.`${SERIES.NOTIFICATION.TABLE}` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `seriesid` INT NOT NULL,
  FOREIGN KEY (`userid`) REFERENCES `${USERS.TABLE}`(`id`),
  FOREIGN KEY (`seriesid`) REFERENCES `${SERIES.TABLE}`(`id`)
  );

ALTER TABLE `${MEDIADOWNLOADER.SCHEMA}`.`${SERIES.NOTIFICATION.TABLE}` ADD UNIQUE INDEX SeriesNotification_userid_seriesid(`userid`, `seriesid`);

